import "Patient.idl";
import "PatientViewModel.idl";
namespace PatientApp
{
    [default_interface]
    runtimeclass AllPatientsPage : Microsoft.UI.Xaml.Controls.Page
    {
        AllPatientsPage();

        PatientViewModel MainViewModel{ get; };
        Patient SelectedPatient;
    }
}
