import "Patient.idl";

namespace PatientApp
{
    [default_interface]
    runtimeclass HomePage : Microsoft.UI.Xaml.Controls.Page
    {
        HomePage();

        Windows.Foundation.Collections.IObservableVector<Patient> PatientsList;
        Patient SelectedPatient;
    }
}
